'use strict';
const $=id=>document.getElementById(id),normalize=s=>s.toLocaleUpperCase('tr-TR').replaceAll('Â','A').replaceAll('Î','İ').replaceAll('Û','U');
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const words=new Set(window.WORDS),stats=read('lingo-stats',{score:0,wins:0,streak:0}),used=new Set(read('lingo-used',[]));let n=5,target='',input='',guesses=[],done=false,busy=false,sound=false,deadline=0,tick=null,token=0;
function evaluate(guess,answer){const result=Array(answer.length).fill('absent'),remaining={};for(let i=0;i<answer.length;i++){if(guess[i]===answer[i])result[i]='correct';else remaining[answer[i]]=(remaining[answer[i]]||0)+1}for(let i=0;i<answer.length;i++)if(result[i]!=='correct'&&remaining[guess[i]]>0){result[i]='present';remaining[guess[i]]--}return result}
function updateStats(){$('score').textContent=stats.score.toLocaleString('tr-TR');$('wins').textContent=stats.wins;$('streak').textContent=stats.streak;save('lingo-stats',stats)}
function message(s,type=''){$('message').textContent=s;$('message').className=type}
function beep(win=false){if(!sound)return;try{const c=audioContext??=new(window.AudioContext||window.webkitAudioContext)();c.resume();const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=win?740:390;g.gain.setValueAtTime(.045,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.start();o.stop(c.currentTime+.17)}catch{}}let audioContext;
function render(){const board=$('board');board.style.maxWidth=n>7?'440px':'';board.style.setProperty('--n',n);board.innerHTML='';for(let r=0;r<6;r++){const row=document.createElement('div');row.className='row'+(r===guesses.length&&!done?' active':'');for(let c=0;c<n;c++){const tile=document.createElement('div'),guess=guesses[r];const ch=guess?guess.word[c]:(r===guesses.length&&!done?input[c]:'');tile.className='tile'+(guess?' '+guess.result[c]:ch?' filled':'');tile.textContent=ch||'';tile.setAttribute('aria-label',ch?ch+(guess?' '+({correct:'doğru yerde',present:'farklı yerde',absent:'yok'}[guess.result[c]]):''):'Boş');row.append(tile)}board.append(row)}$('attempt').textContent=`${Math.min(guesses.length+1,6)} / 6 TAHMİN`;$('round').textContent=`${n} HARFLİ KELİME`;const ranks={absent:1,present:2,correct:3},keys={};guesses.forEach(g=>[...g.word].forEach((l,i)=>{if((ranks[g.result[i]]||0)>(ranks[keys[l]]||0))keys[l]=g.result[i]}));document.querySelectorAll('.key').forEach(k=>{k.className='key'+(k.dataset.key.length>1?' wide':'')+(keys[k.dataset.key]?' '+keys[k.dataset.key]:'');k.disabled=done||busy});$('next').hidden=!done}
function timer(){clearInterval(tick);$('timerWrap').hidden=!$('timed').checked;if(!$('timed').checked||done)return;deadline=Date.now()+30000;const update=()=>{let left=Math.max(0,deadline-Date.now());$('seconds').textContent=Math.ceil(left/1000)+' sn';$('timer').style.width=(left/300)+'%';if(left===0&&!busy){clearInterval(tick);finish(false,'Süre doldu.')}};update();tick=setInterval(update,200)}
function start(){token++;clearInterval(tick);let pool=window.WORDS.filter(w=>w.length===n),available=pool.filter(w=>!used.has(w));if(!available.length){pool.forEach(w=>used.delete(w));available=pool.filter(w=>w!==target);if(!available.length)available=pool}target=available[Math.floor(Math.random()*available.length)];used.add(target);save('lingo-used',[...used]);input=target[0];guesses=[];done=false;busy=false;$('confetti').innerHTML='';$('pool').textContent=pool.length.toLocaleString('tr-TR');document.querySelectorAll('.lengths button').forEach(b=>{b.classList.toggle('selected',+b.dataset.n===n);b.setAttribute('aria-pressed',String(+b.dataset.n===n))});render();message(`“${target[0]}” ile başlayan ${n} harfli bir kelime yaz.`);timer()}
function finish(win,prefix=''){done=true;busy=false;clearInterval(tick);if(win){const pts=(7-guesses.length)*n*10;stats.score+=pts;stats.wins++;stats.streak++;message(`Harika! ${target} · +${pts} puan`,'success');beep(true);$('confetti').innerHTML=Array.from({length:45},(_,i)=>`<i style="left:${Math.random()*100}%;background:${i%2?'#b9e776':'#f7aa71'};animation-delay:${Math.random()*.6}s"></i>`).join('')}else{stats.streak=0;message(`${prefix||'Bu kez olmadı.'} Kelime: ${target}`,'error')}updateStats();render()}
function submit(){if(done||busy)return;if(input.length!==n){message(`${n} harfli bir kelime yazmalısın.`,'error');shake();return}if(!words.has(input)){message('Bu kelime sözlükte bulunamadı. Başka bir kelime dene.','error');shake();return}if(guesses.some(g=>g.word===input)){message('Bu kelimeyi zaten denedin.','error');shake();return}clearInterval(tick);busy=true;const guess=input;guesses.push({word:guess,result:evaluate(guess,target)});render();const row=$('board').children[guesses.length-1];[...row.children].forEach((t,i)=>{t.classList.add('reveal');t.style.setProperty('--delay',i*70+'ms')});beep();const thisToken=token;setTimeout(()=>{if(thisToken!==token)return;busy=false;if(guess===target){finish(true);return}if(guesses.length===6){finish(false);return}input=target[0];render();message('Renkleri takip et. Sıradaki tahminin?');timer()},n*70+400)}
function shake(){const row=$('board').children[guesses.length];row?.classList.add('shake');setTimeout(()=>row?.classList.remove('shake'),400)}
function type(key){if(done||busy||$('modal').open)return;if($('timed').checked&&Date.now()>=deadline){finish(false,'Süre doldu.');return}if(key==='Enter'){submit();return}if(key==='Backspace'){input=input.slice(0,-1)}else{key=normalize(key);if(!/^[ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ]$/.test(key)||input.length>=n)return;input+=key}render()}
for(let i=4;i<=10;i++){const b=document.createElement('button');b.textContent=i;b.dataset.n=i;b.setAttribute('aria-label',i+' harf');b.onclick=()=>{if(n===i)return;confirmChange(()=>{n=i;start()})};$('lengths').append(b)}
['ERTYUIOPĞÜ','ASDFGHJKLŞİ','ZCVBNMÖÇ','Enter Backspace'].forEach((str,i)=>{const row=document.createElement('div');row.className='keyrow';const keys=i===3?str.split(' '):[...str];keys.forEach(k=>{const b=document.createElement('button');b.className='key'+(k.length>1?' wide':'');b.dataset.key=k;b.textContent=k==='Enter'?'GÖNDER':k==='Backspace'?'⌫ SİL':k;b.setAttribute('aria-label',k==='Enter'?'Tahmini gönder':k==='Backspace'?'Son harfi sil':k);b.onclick=()=>type(k);row.append(b)});$('keyboard').append(row)});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||$('modal').open||['BUTTON','INPUT'].includes(document.activeElement.tagName)&&e.key==='Enter')return;if(e.key==='Enter'||e.key==='Backspace'||/^[a-zA-ZçğıöşüÇĞİÖŞÜ]$/.test(e.key)){e.preventDefault();type(e.key)}});
function modal(html){$('modalBody').innerHTML=html;$('modal').showModal()}function confirmChange(fn){if(!done&&(guesses.length||input.length>1)){modal('<h2>Yeni oyuna geçilsin mi?</h2><p>Bu kelimedeki tahminlerin silinecek.</p><button class="primary" id="confirmChange">Yeni oyuna geç</button>');$('confirmChange').onclick=()=>{$('modal').close();fn()}}else fn()}
$('timed').onchange=()=>{const next=$('timed').checked;$('timed').checked=!next;confirmChange(()=>{$('timed').checked=next;start()})};$('next').onclick=start;$('close').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close()}};
$('help').onclick=()=>modal('<span class="eyebrow">HOŞ GELDİN</span><h2>Bir kelime. Altı tahmin.</h2><p>İlk harfi verilen kelimeyi 6 tahminde bul. 4–10 harf arasından seçim yap. Ekrandaki ya da fiziksel klavyeni kullan.</p><div class="legend"><i class="correct"></i> Yeşil: harf doğru yerde.</div><div class="legend"><i class="present"></i> Turuncu: harf başka bir yerde.</div><div class="legend"><i class="absent"></i> Gri: bu harften başka yok.</div><p>Tekrarlanan harfler kelimedeki sayısı kadar renklendirilir. I ve İ farklı harflerdir; şapkalı harfler düz yazılır. Süreli modda her tahmin için 30 saniyen var. Geçersiz tahminler süreyi yenilemez.</p><p>Puan = kalan tahmin hakkı (doğru tahmin dahil) × harf sayısı × 10. Kelimeler, seçilen uzunluktaki havuz bitmeden tekrarlanmaz.</p>');
$('source').onclick=()=>modal('<h2>38.910 kelimelik keşif</h2><p>4–10 harfli, Türkçe harflerden oluşan tek sözcükler kullanılır. Büyük harfle başlayan özel adlar ve çok sözcüklü ifadeler elenmiştir. Sözlük, eski ve az kullanılan sözcükler de içerir.</p><p>Kaynak: <a href="https://github.com/mertemin/turkish-word-list" target="_blank" rel="noopener noreferrer">VikiSözlük tabanlı Türkçe kelime listesi</a>. Harf normalleştirmesi ve oyun filtreleri uygulanmıştır.</p><p>Havuz sonludur; her uzunluktaki kelimeler bitince yeni bir karışık tur başlar. Oyun sırasında sözlük için harici hizmete ihtiyaç duyulmaz.</p>');
$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Sesi kapat':'Sesi aç');$('sound').style.color=sound?'var(--green)':'';beep()};updateStats();start();
